// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopSphere.UserService.Persistence.DbContexts;

#nullable disable

namespace ShopSphere.UserService.Persistence.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    [Migration("20241117160752_SeedUsers")]
    partial class SeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopSphere.UserService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("2d7ad514-a50d-4d33-a5d6-d8e354feff06"),
                            CreatedAt = new DateTime(2024, 11, 17, 16, 7, 51, 936, DateTimeKind.Utc).AddTicks(7660),
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$0fd3m8CJobJmdiQS5skdruucb8Ym71rvsIwNDXV9J1Sly6HZfhVI2",
                            Role = 0,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = new Guid("47433a37-f80e-48fc-9f00-abde68799826"),
                            CreatedAt = new DateTime(2024, 11, 17, 16, 7, 52, 78, DateTimeKind.Utc).AddTicks(19),
                            Email = "user@example.com",
                            PasswordHash = "$2a$11$wEZVYLkFpdFXyBePNzHclOGvQSkRxvfcdGbO6BZVhV5Iiw9lnaHTi",
                            Role = 1,
                            Username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
