// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopSphere.UserService.Persistence.DbContexts;

#nullable disable

namespace ShopSphere.UserService.Persistence.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopSphere.UserService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("57e3bac9-ff2d-4ff3-a9e2-330a4bd0eece"),
                            CreatedAt = new DateTime(2024, 11, 17, 16, 12, 29, 189, DateTimeKind.Utc).AddTicks(4844),
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$Lwmq0x.VgRs6rf7ncBfNA.sFXWlADeSjcz4lotxuJqLgsk7dFzC0S",
                            Role = 0,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = new Guid("f4c2c5f4-8be7-4c2f-a653-69bc46070f2b"),
                            CreatedAt = new DateTime(2024, 11, 17, 16, 12, 29, 325, DateTimeKind.Utc).AddTicks(4473),
                            Email = "user@example.com",
                            PasswordHash = "$2a$11$MZncmIetucdSzXrIAko2O.0MDw1qA880Co31.NocW6nFqGaE.Luni",
                            Role = 1,
                            Username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
